### ISSUE TITLE
Create page to show Entities that received the most money in order.

### ISSUE THREAD

**Issue by carlosplf** [carlosplf/br_data_inspector#10]
### TODO list for the Issue:

- [x] Create a DataProcessor to build lists and ranks.
- [x] Modify the run.py file so it can run the DataProcessor.
- [x] Modify the API to collect entities list from Redis.
- [x] Add route to API to entities rank.
- [x] Create page and menu to show Entities rank.
- [x] Update README and Documentation about this implementation.

**Comment by carlosplf** [comment]
Since we have lots of data, maybe a good way to to this is to create another backend routine to build the entitites ranks.
RedisDB seens like a good option to store these ranks.

**Comment by carlosplf** [comment]
Using branch "data_rank" to do it.

**Comment by carlosplf** [comment]
Table could have a better CSS. But, as an enhancement, should be another Issue.
